config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # homepage default
  root to: 'pages#home'

  # path to month with date in the URL /salaries/1/pay_slips/1?start_date=2019-12-01
  get "/id:?start_date=:month", to: "pay_slips#show"

  # resources :pages

  resources :salaries, only: [:index, :show, :new, :create, :edit, :update] do
    resources :pay_slips do
      resources :days
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :salaries do
        resources :pay_slips do
          resources :days, only: [:index]
        end
      end
    end
  end


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("logo.png") %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
<!--        <li class="nav-item active">-->
          <%#= link_to "Home", "/", class: "nav-link" %>
<!--        </li>-->
        <li class="nav-item dropdown">
          <%= link_to "Salaries", "#", class: "nav-link dropdown-toggle", id: "navbarDropdown1", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown1">
            <%= link_to "New Salary Setup", new_salary_path , class: "dropdown-item" %>
            <%= link_to "View all Salaries", salaries_path, class: "dropdown-item" %>
            <%= link_to "New Salary Setup", new_salary_path, class: "dropdown-item" %>
            <%= link_to "New Month Salary", "#make_by_default_current_user_last_created_salary_then_new_salary_pay_slip_url(this)", class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "http://simpleicon.com/wp-content/uploads/user1-256x256.png", class: "avatar dropdown-toggle", id: "navbarDropdown2", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown2">
            <%= link_to "Edit My Account", edit_user_registration_path , class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>