config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # homepage default
  root to: 'pages#home'

  # path to month with date in the URL /salaries/1/pay_slips/1?start_date=2019-12-01
  get "/id:?start_date=:month", to: "pay_slips#show"

  # resources :pages

  resources :salaries, only: [:index, :show, :new, :create, :edit, :update] do
    resources :pay_slips do
      resources :days
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :salaries do
        resources :pay_slips do
          resources :days, only: [:index]
        end
      end
    end
  end


end

app/models/salary.rb
# Salary Schema
# id: integer
# user_id: integer
# contract_type: string
# hourly_rate_cents: integer
# hourly_rate_currency: string
# starting_hour: time
# ending_hour: time
# day_per_week: integer
# working_on_banks_holliday: boolean
# cleaning_cost_cents: integer
# cleaning_cost_currency: string
# meal_cost_cents: integer
# meal_cost_currency: string
# daily_meals: integer
# created_at: datetime
# updated_at: datetime
# belongs_to :user
# has_many :pay_slips

class Salary < ApplicationRecord
  belongs_to :user
  has_many :pay_slips

  #validations
  validates :contract_type, :hourly_rate_cents, :starting_hour, :ending_hour, :day_per_week,  presence: true
  validates :contract_type, inclusion: { in: %w(mensualisé horaire),  message: "%{value} n'est pas un type de contract valide" }
  # custom validation function
 # validates :starting_hour_is_before_ending_hour



  #money rails
  monetize :hourly_rate_cents, with_model_currency: :currency
  monetize :meal_cost_cents, with_model_currency: :currency
  monetize :cleaning_cost_cents, with_model_currency: :currency

  def starting_hour_is_before_ending_hour
    if starting_hour > ending_hour
      errors.add(:starting_hour, "can't be greater than ending_hour")
    end
  end


end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def index
    @salaries = Salary.where(user_id: @user)
  end

  def show
    @salary = Salary.find(params[:id])
  end

  def new
    @salary = Salary.new()
    @salary.user = @user
  end

  def create
    @salary = Salary.new(salary_params)
    @salary.user = @user
    if @salary.save!
      redirect_to salary_path(@salary)
    else
      alert
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def salary_params
    params.require(:salary).permit(:contract_type, :hourly_rate_cents, :starting_hour, :ending_hour, :day_per_week, :working_on_banks_holliday, :cleaning_cost_cents, :meal_cost_cents, :daily_meals)
  end

  def set_user
    @user = current_user
  end
end

app/views/salaries/edit.html.erb
<h1>Salaries#edit</h1>
<p>Find me in app/views/salaries/edit.html.erb</p>

app/views/salaries/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1>List of your Salary Setup</h1>
    <ul>
      <% @salaries.each do |salary|  %>
        <li>
          Contract <%= salary.contract_type %> created on <%= salary.created_at.to_time.strftime('%B %e') %>
          <%=  link_to "Update", edit_salary_path(salary) %>
          <%=  link_to "View Detail", salary_path(salary) %>
          <%=  link_to "view all salary slip", salary_pay_slips_path(salary) %>
          <%=  link_to "create a new salary slip", new_salary_pay_slip_path(salary) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/salaries/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1>New Salaries Setup</h1>
    <%= simple_form_for @salary do |f| %>
      <%= f.error_notification %>
      <%= f.input :contract_type, collection: %w(mensualisé horaire), default: "mensualisé"%>
      <%= f.input  :hourly_rate, input_html: { value: '3.50' } %>
      <%= f.input  :starting_hour %>
      <%= f.input  :ending_hour %>
      <%= f.input  :day_per_week,  input_html: { value: '5' }%>
      <%= f.input  :working_on_banks_holliday, as: :radio_buttons, wrapper: :vertical_collection_inline ,  input_html: { value: 'false' }%>
      <%= f.input  :cleaning_cost, input_html: { value: '3.50' } %>
      <%= f.input  :meal_cost, input_html: { value: '3.50' } %>
      <%= f.input  :daily_meals, input_html: { value: '1' } %>
      <%= f.button :submit, class: "btn-primary" %>
    <% end %>
  </div>
</div>

<!--:hourly_rate_cents,-->
<!--:starting_hour,-->
<!--:ending_hour,-->
<!--:day_per_week,-->
<!--:working_on_banks_holliday,-->
<!--:cleaning_cost_cents,-->
<!--:meal_cost_cents,-->
<!--:daily_meals-->

app/views/salaries/show.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Detail of Salary Set Up </h1>
    <ul>
      <li><strong>Contract_type</strong> <%= @salary.contract_type %></li>
      <li><strong>hourly_rate_cents</strong> <%= @salary.hourly_rate_cents %></li>
      <li><strong>hourly_rate_currency</strong><%= @salary.hourly_rate_currency %></li>
      <li><strong>starting_hour</strong><%= @salary.starting_hour %></li>
      <li><strong>ending_hour</strong><%= @salary.ending_hour %></li>
      <li><strong>day_per_week</strong><%= @salary.day_per_week %></li>
      <li><strong>working_on_banks_holliday</strong><%= @salary.working_on_banks_holliday %></li>
      <li><strong>cleaning_cost_cents</strong><%= @salary.cleaning_cost_cents %></li>
      <li><strong>cleaning_cost_currency</strong><%= @salary.cleaning_cost_currency %></li>
      <li><strong>meal_cost_cents</strong><%= @salary.meal_cost_cents %></li>
      <li><strong>meal_cost_currency</strong><%= @salary.meal_cost_currency %></li>
      <li><strong>daily_meal</strong><%= @salary.daily_meals %></li>
    </ul>
  </div>
</div>