config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # homepage default
  root to: 'pages#home'

  # path to month with date in the URL /salaries/1/pay_slips/1?start_date=2019-12-01
  get "/id:?start_date=:month", to: "pay_slips#show"

  # resources :pages

  resources :salaries, only: [:index, :show, :new, :create, :edit, :update] do
    resources :pay_slips do
      resources :days
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :salaries do
        resources :pay_slips do
          resources :days, only: [:index]
        end
      end
    end
  end


end

app/models/pay_slip.rb
# PaySlip schema
# id: integer
# month: datetime
# salary_id: integer
# created_at: datetime
# updated_at: datetime
# belongs_to :salary

class PaySlip < ApplicationRecord
  belongs_to :salary
  has_many :days
end

app/controllers/pay_slips_controller.rb
class PaySlipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_salary_setup


  def index
    @payslips = PaySlip.where(salary: @salary)
  end

  def show
    @pay_slip = PaySlip.find(params[:id])
    @pay_slip_first_day = @pay_slip.month.to_date
    @pay_slip_last_day = end_of_month(@pay_slip_first_day)
    @this_month_days = Day.where(pay_slip_id: @pay_slip)
  end

  def new
    @pay_slip = PaySlip.new()
  end

  def create
    @pay_slip = PaySlip.new(pay_slip_params)
    @pay_slip.salary = @salary
    if @pay_slip.save!
      @pay_slip_first_day = @pay_slip.month.to_date
      @pay_slip_last_day = end_of_month(@pay_slip_first_day)
      @this_month_days = month_date_array(@pay_slip_first_day, @pay_slip_last_day)
      generate_days_entries(@salary,@pay_slip,@this_month_days)
      redirect_to salary_pay_slip_path(@salary, @pay_slip)
    else
      alert
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def set_salary_setup
    @salary = Salary.find(params[:salary_id])
  end

  def pay_slip_params
    params.require(:pay_slip).permit(:month,:salary_id)
  end

  def end_of_month(beginning_of_the_month)
    return Date.new(beginning_of_the_month.year, beginning_of_the_month.month, -1)
  end

  #  create an array of all possible date in the array bewteen  @pay_slip_first_day & @pay_slip_last_day
  def month_date_array(date_begin, date_end)
    days = []
    date_begin.step(date_end).each{|d| days.push(d)}
    return days
  end


  #  for each element of the @days array create a Day class element that, depending on it weekday takes the default parameters defined in the salary
  def generate_days_entries(salary, pay_slip, array_of_days)
    std_starting_hours = salary.starting_hour
    std_ending_hours  = salary.ending_hour
    std_meals = salary.daily_meals
    week_days = [1,2,3,4,5]
    # TODO need a way to get the date of bank holliday in france. this gem seems nice :
    # https://github.com/gocardless/business I could use it's method business_day? false + not a week end (saturday? sunday?)
    array_of_days.each do |d|
      if week_days.include?(d.wday)
        a =  Day.new(day_date: d,
                     pay_slip_id: pay_slip.id,
                     status: "worked",
                     starting_hour: std_starting_hours,
                     ending_hour: std_ending_hours,
                     daily_meal: std_meals)
        a.save!
      else
        a = Day.new(day_date: d,
                    pay_slip_id: pay_slip.id,
                    status: "weekend",
                    starting_hour: Time.new(0),
                    ending_hour: Time.new(0),
                    daily_meal: 0)
        a.save
      end
    end
    # if it s a week day
    # create a days with :day_date,  :status, :starting_hour, :ending_hour, :daily_meal
    # if it's a week end day
    # create a day with :day_date, :status "week end", starting_hour: 00:00 endin_hour: 00:00, daily_meal: 0
  end


end

app/views/pay_slips/edit.html.erb
<h1>PaySlips#edit</h1>
<p>Find me in app/views/pay_slips/edit.html.erb</p>

app/views/pay_slips/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1>PaySlips#new</h1>
    <p>Find me in app/views/pay_slips/new.html.erb</p>
    <div class="wrapper">
      <div class="container">
        <h1>New Salaries Setup</h1>
        <%= simple_form_for [@salary,@pay_slip] do |f| %>
          <%= f.error_notification %>
          <%= f.input :month, as: :date %>
          <%= f.button :submit, class: "btn-primary" %>
        <% end %>
      </div>
    </div>
</div>
</div>


<script type="text/javascript" charset="utf-8">
  // TODO : make it through a calendar picker instead of a form
   let dDay = document.getElementById('pay_slip_month_3i');
  // hide the day for month it need to be the 1st day of the month
  dDay.style.display = 'none';
  // set the default day to 1st day of the month
  dDay.value = 1;
</script>

app/views/pay_slips/show.html.erb
<div class="wrapper">
  <div class="container">
    <h1>PaySlips#show</h1>
    <p>Find me in app/views/pay_slips/show.html.erb</p>

    <h2>Some data</h2>
    <p>
      Salary : <%= @salary %> <br>
      Pay slip : <%= @pay_slip %><br>
      Pay slip month 1st day: <%= @pay_slip_first_day %> of class <%= @pay_slip_first_day.class %><br>
      Pay slip month last day: <%= @pay_slip_last_day %> of class <%= @pay_slip_last_day.class %><br>
      All dates to consider this month :<br>
<!--      TODO : inject this data into the calendar-->
      <% @this_month_days.each do |day| %>
        <%= day.status  %> On <%= day.day_date %>  from   <%= day.starting_hour %> till <%= day.ending_hour %> made <%= day.daily_meal %> meals </br>
    <%end %>
    </p>


    <h2>A calendar</h2>
    <%= month_calendar  do |date| %>
      <%= link_to date, new_salary_pay_slip_day_path(@salary, @pay_slip) %>
    <% end %>
  </div>
</div>

<!-- TODO : move this script to assets -->



<script type="text/javascript" charset="utf-8">
  // const previousMonthDays = document.querySelectorAll(".prev-month")
  // const futureMonthDays = document.querySelectorAll(".next-month")

  const days = Array.from(document.querySelectorAll(".current-month"));
  // console.log(days);
  // days.addEventListener(onclick, clickOnDayFunction);
  days.forEach(day => day.addEventListener('click', handleClickOnDay));
  function handleClickOnDay(e) {
      console.log(e.target.innerText);
  }







  // function clickOnDayFunction(e){
  //     const selectedDay = e.innerText ;
  //     console.log(selectedDay);
  // }


</script>